// appointments actions
export const SET_APPOINTMENTS_REQUEST = 'SET_APPOINTMENTS_REQUEST';
export const SET_APPOINTMENTS_LIST = 'SET_APPOINTMENTS_LIST';
export const HANDLE_APPOINTMENTS_ERROR = 'HANDLE_APPOINTMENTS_ERROR';


// appointments actions
export const HANDLE_BOOKING_ERROR = 'HANDLE_BOOKING_ERROR';

export const SET_CHOOSE_APPOINTMENT = 'SET_CHOOSE_APPOINTMENT';
export const SET_PERSONAL_INFO = 'SET_PERSONAL_INFO';

export const HANDLE_ALL_BOOKINGS_ERROR = 'HANDLE_ALL_BOOKINGS_ERROR';
export const GET_ALL_BOOKINGS_REQUEST = 'GET_ALL_BOOKINGS_REQUEST';
export const SET_ALL_BOOKINGS = 'SET_ALL_BOOKINGS';