// get appointments actions
export const SET_APPOINTMENTS_REQUEST = 'SET_APPOINTMENTS_REQUEST';
export const SET_APPOINTMENTS_LIST = 'SET_APPOINTMENTS_LIST';
export const HANDLE_APPOINTMENTS_ERROR = 'HANDLE_APPOINTMENTS_ERROR';

// get all bookings actions
export const HANDLE_ALL_BOOKINGS_ERROR = 'HANDLE_ALL_BOOKINGS_ERROR';
export const GET_ALL_BOOKINGS_REQUEST = 'GET_ALL_BOOKINGS_REQUEST';
export const SET_ALL_BOOKINGS = 'SET_ALL_BOOKINGS';

// booking actions
export const SET_CHOOSE_APPOINTMENT = 'SET_CHOOSE_APPOINTMENT';

export const COMPLETE_NEW_BOOKING_REQUEST = 'COMPLETE_NEW_BOOKING_REQUEST';
export const SET_NEW_BOOKING = 'ADD_NEW_BOOKING';
export const HANDLE_BOOKING_ERROR = 'HANDLE_BOOKING_ERROR';

export const CANCEL_BOOKING_REQUEST = 'CANCEL_BOOKING_REQUEST';
export const CANCEL_BOOKING = 'CANCEL_BOOKING';

export const RESCHEDULE_BOOKING_REQUEST = 'RESCHEDULE_BOOKING_REQUEST';
export const RESCHEDULE_BOOKING = 'RESCHEDULE_BOOKING';

export const SCHEDULE_ANOTHER_BOOKING = 'SCHEDULE_ANOTHER_BOOKING';
